package com.example.currency.currency_extention

import androidx.annotation.StringRes
import com.example.currency.R
import com.example.currency.currency_cod.CurrencyCod

@StringRes
fun CurrencyCod.stringRes(): Int {
    return when (this) {
        CurrencyCod.AED -> R.string.currency_name_aed
        CurrencyCod.AFN -> R.string.currency_name_afn
        CurrencyCod.ALL -> R.string.currency_name_all
        CurrencyCod.AMD -> R.string.currency_name_amd
        CurrencyCod.ANG -> R.string.currency_name_ang
        CurrencyCod.AOA -> R.string.currency_name_aoa
        CurrencyCod.ARS -> R.string.currency_name_ars
        CurrencyCod.AUD -> R.string.currency_name_aud
        CurrencyCod.AWG -> R.string.currency_name_awg
        CurrencyCod.AZN -> R.string.currency_name_azn
        CurrencyCod.BAM -> R.string.currency_name_bam
        CurrencyCod.BBD -> R.string.currency_name_bbd
        CurrencyCod.BDT -> R.string.currency_name_bdt
        CurrencyCod.BGN -> R.string.currency_name_bgn
        CurrencyCod.BHD -> R.string.currency_name_bhd
        CurrencyCod.BIF -> R.string.currency_name_bif
        CurrencyCod.BMD -> R.string.currency_name_bmd
        CurrencyCod.BND -> R.string.currency_name_bnd
        CurrencyCod.BOB -> R.string.currency_name_bob
        CurrencyCod.BRL -> R.string.currency_name_brl
        CurrencyCod.BSD -> R.string.currency_name_bsd
        CurrencyCod.BTN -> R.string.currency_name_btn
        CurrencyCod.BWP -> R.string.currency_name_bwp
        CurrencyCod.BYN -> R.string.currency_name_byn
        CurrencyCod.BZD -> R.string.currency_name_bzd
        CurrencyCod.CAD -> R.string.currency_name_cad
        CurrencyCod.CDF -> R.string.currency_name_cdf
        CurrencyCod.CHF -> R.string.currency_name_chf
        CurrencyCod.CLF -> R.string.currency_name_clf
        CurrencyCod.CKD -> R.string.currency_name_ckd
        CurrencyCod.CLP -> R.string.currency_name_clp
        CurrencyCod.CNY -> R.string.currency_name_cny
        CurrencyCod.COP -> R.string.currency_name_cop
        CurrencyCod.CRC -> R.string.currency_name_crc
        CurrencyCod.CUC -> R.string.currency_name_cuc
        CurrencyCod.CUP -> R.string.currency_name_cup
        CurrencyCod.CVE -> R.string.currency_name_cve
        CurrencyCod.CZK -> R.string.currency_name_czk
        CurrencyCod.DJF -> R.string.currency_name_djf
        CurrencyCod.DKK -> R.string.currency_name_dkk
        CurrencyCod.DOP -> R.string.currency_name_dop
        CurrencyCod.DZD -> R.string.currency_name_dzd
        CurrencyCod.EGP -> R.string.currency_name_egp
        CurrencyCod.ERN -> R.string.currency_name_ern
        CurrencyCod.ETB -> R.string.currency_name_etb
        CurrencyCod.EUR -> R.string.currency_name_eur
        CurrencyCod.FJD -> R.string.currency_name_fjd
        CurrencyCod.FKP -> R.string.currency_name_fkp
        CurrencyCod.FOK -> R.string.currency_name_fok
        CurrencyCod.GBP -> R.string.currency_name_gbp
        CurrencyCod.GEL -> R.string.currency_name_gel
        CurrencyCod.GGP -> R.string.currency_name_ggp
        CurrencyCod.GHS -> R.string.currency_name_ghs
        CurrencyCod.GIP -> R.string.currency_name_gip
        CurrencyCod.GMD -> R.string.currency_name_gmd
        CurrencyCod.GNF -> R.string.currency_name_gnf
        CurrencyCod.GTQ -> R.string.currency_name_gtq
        CurrencyCod.GYD -> R.string.currency_name_gyd
        CurrencyCod.HKD -> R.string.currency_name_hkd
        CurrencyCod.HNL -> R.string.currency_name_hnl
        CurrencyCod.HRK -> R.string.currency_name_hrk
        CurrencyCod.HTG -> R.string.currency_name_htg
        CurrencyCod.HUF -> R.string.currency_name_huf
        CurrencyCod.IDR -> R.string.currency_name_idr
        CurrencyCod.ILS -> R.string.currency_name_ils
        CurrencyCod.IMP -> R.string.currency_name_imp
        CurrencyCod.INR -> R.string.currency_name_inr
        CurrencyCod.IQD -> R.string.currency_name_iqd
        CurrencyCod.IRR -> R.string.currency_name_irr
        CurrencyCod.ISK -> R.string.currency_name_isk
        CurrencyCod.JEP -> R.string.currency_name_jep
        CurrencyCod.JMD -> R.string.currency_name_jmd
        CurrencyCod.JOD -> R.string.currency_name_jod
        CurrencyCod.JPY -> R.string.currency_name_jpy
        CurrencyCod.KES -> R.string.currency_name_kes
        CurrencyCod.KID -> R.string.currency_name_kid
        CurrencyCod.KGS -> R.string.currency_name_kgs
        CurrencyCod.KHR -> R.string.currency_name_khr
        CurrencyCod.KMF -> R.string.currency_name_kmf
        CurrencyCod.KPW -> R.string.currency_name_kpw
        CurrencyCod.KRW -> R.string.currency_name_krw
        CurrencyCod.KWD -> R.string.currency_name_kwd
        CurrencyCod.KYD -> R.string.currency_name_kyd
        CurrencyCod.KZT -> R.string.currency_name_kzt
        CurrencyCod.LAK -> R.string.currency_name_lak
        CurrencyCod.LBP -> R.string.currency_name_lbp
        CurrencyCod.LKR -> R.string.currency_name_lkr
        CurrencyCod.LRD -> R.string.currency_name_lrd
        CurrencyCod.LSL -> R.string.currency_name_lsl
        CurrencyCod.LYD -> R.string.currency_name_lyd
        CurrencyCod.MAD -> R.string.currency_name_mad
        CurrencyCod.MDL -> R.string.currency_name_mdl
        CurrencyCod.MGA -> R.string.currency_name_mga
        CurrencyCod.MKD -> R.string.currency_name_mkd
        CurrencyCod.MMK -> R.string.currency_name_mmk
        CurrencyCod.MNT -> R.string.currency_name_mnt
        CurrencyCod.MOP -> R.string.currency_name_mop
        CurrencyCod.MRU -> R.string.currency_name_mru
        CurrencyCod.MUR -> R.string.currency_name_mur
        CurrencyCod.MVR -> R.string.currency_name_mvr
        CurrencyCod.MWK -> R.string.currency_name_mwk
        CurrencyCod.MXN -> R.string.currency_name_mxn
        CurrencyCod.MYR -> R.string.currency_name_myr
        CurrencyCod.MZN -> R.string.currency_name_mzn
        CurrencyCod.NAD -> R.string.currency_name_nad
        CurrencyCod.NGN -> R.string.currency_name_ngn
        CurrencyCod.NIO -> R.string.currency_name_nio
        CurrencyCod.NOK -> R.string.currency_name_nok
        CurrencyCod.NPR -> R.string.currency_name_npr
        CurrencyCod.NZD -> R.string.currency_name_nzd
        CurrencyCod.OMR -> R.string.currency_name_omr
        CurrencyCod.PAB -> R.string.currency_name_pab
        CurrencyCod.PEN -> R.string.currency_name_pen
        CurrencyCod.PGK -> R.string.currency_name_pgk
        CurrencyCod.PHP -> R.string.currency_name_php
        CurrencyCod.PKR -> R.string.currency_name_pkr
        CurrencyCod.PLN -> R.string.currency_name_pln
        CurrencyCod.PYG -> R.string.currency_name_pyg
        CurrencyCod.QAR -> R.string.currency_name_qar
        CurrencyCod.RON -> R.string.currency_name_ron
        CurrencyCod.RSD -> R.string.currency_name_rsd
        CurrencyCod.RUB -> R.string.currency_name_rub
        CurrencyCod.RWF -> R.string.currency_name_rwf
        CurrencyCod.SAR -> R.string.currency_name_sar
        CurrencyCod.SBD -> R.string.currency_name_sbd
        CurrencyCod.SCR -> R.string.currency_name_scr
        CurrencyCod.SDG -> R.string.currency_name_sdg
        CurrencyCod.SEK -> R.string.currency_name_sek
        CurrencyCod.SGD -> R.string.currency_name_sgd
        CurrencyCod.SHP -> R.string.currency_name_shp
        CurrencyCod.SLL -> R.string.currency_name_sll
        CurrencyCod.SOS -> R.string.currency_name_sos
        CurrencyCod.SRD -> R.string.currency_name_srd
        CurrencyCod.SSP -> R.string.currency_name_ssp
        CurrencyCod.STN -> R.string.currency_name_stn
        CurrencyCod.SVC -> R.string.currency_name_svc
        CurrencyCod.SYP -> R.string.currency_name_syp
        CurrencyCod.SZL -> R.string.currency_name_szl
        CurrencyCod.THB -> R.string.currency_name_thb
        CurrencyCod.TJS -> R.string.currency_name_tjs
        CurrencyCod.TMT -> R.string.currency_name_tmt
        CurrencyCod.TND -> R.string.currency_name_tnd
        CurrencyCod.TOP -> R.string.currency_name_top
        CurrencyCod.TRY -> R.string.currency_name_try
        CurrencyCod.TTD -> R.string.currency_name_ttd
        CurrencyCod.TVD -> R.string.currency_name_tvd
        CurrencyCod.TWD -> R.string.currency_name_twd
        CurrencyCod.TZS -> R.string.currency_name_tzs
        CurrencyCod.UAH -> R.string.currency_name_uah
        CurrencyCod.UGX -> R.string.currency_name_ugx
        CurrencyCod.USD -> R.string.currency_name_usd
        CurrencyCod.UYU -> R.string.currency_name_uyu
        CurrencyCod.UZS -> R.string.currency_name_uzs
        CurrencyCod.VEF -> R.string.currency_name_vef
        CurrencyCod.VES -> R.string.currency_name_ves
        CurrencyCod.VND -> R.string.currency_name_vnd
        CurrencyCod.VUV -> R.string.currency_name_vuv
        CurrencyCod.WST -> R.string.currency_name_wst
        CurrencyCod.XAF -> R.string.currency_name_xaf
        CurrencyCod.XCD -> R.string.currency_name_xcd
        CurrencyCod.XOF -> R.string.currency_name_xof
        CurrencyCod.XPF -> R.string.currency_name_xpf
        CurrencyCod.YER -> R.string.currency_name_yer
        CurrencyCod.ZAR -> R.string.currency_name_zar
        CurrencyCod.ZMW -> R.string.currency_name_zmw
        CurrencyCod.ZWL -> R.string.currency_name_zwl
    }
}
