package com.example.currency.currency_extention

import androidx.annotation.StringRes
import com.example.currency.R
import com.example.currency.currencн.CurrencyFlagList

@StringRes
fun CurrencyFlagList.stringRes(): Int {
    return when (this) {
        CurrencyFlagList.AED -> R.string.currency_name_aed
        CurrencyFlagList.AFN -> R.string.currency_name_afn
        CurrencyFlagList.ALL -> R.string.currency_name_all
        CurrencyFlagList.AMD -> R.string.currency_name_amd
        CurrencyFlagList.ANG -> R.string.currency_name_ang
        CurrencyFlagList.AOA -> R.string.currency_name_aoa
        CurrencyFlagList.ARS -> R.string.currency_name_ars
        CurrencyFlagList.AUD -> R.string.currency_name_aud
        CurrencyFlagList.AWG -> R.string.currency_name_awg
        CurrencyFlagList.AZN -> R.string.currency_name_azn
        CurrencyFlagList.BAM -> R.string.currency_name_bam
        CurrencyFlagList.BBD -> R.string.currency_name_bbd
        CurrencyFlagList.BDT -> R.string.currency_name_bdt
        CurrencyFlagList.BGN -> R.string.currency_name_bgn
        CurrencyFlagList.BHD -> R.string.currency_name_bhd
        CurrencyFlagList.BIF -> R.string.currency_name_bif
        CurrencyFlagList.BMD -> R.string.currency_name_bmd
        CurrencyFlagList.BND -> R.string.currency_name_bnd
        CurrencyFlagList.BOB -> R.string.currency_name_bob
        CurrencyFlagList.BRL -> R.string.currency_name_brl
        CurrencyFlagList.BSD -> R.string.currency_name_bsd
        CurrencyFlagList.BTN -> R.string.currency_name_btn
        CurrencyFlagList.BWP -> R.string.currency_name_bwp
        CurrencyFlagList.BYN -> R.string.currency_name_byn
        CurrencyFlagList.BZD -> R.string.currency_name_bzd
        CurrencyFlagList.CAD -> R.string.currency_name_cad
        CurrencyFlagList.CDF -> R.string.currency_name_cdf
        CurrencyFlagList.CHF -> R.string.currency_name_chf
        CurrencyFlagList.CLF -> R.string.currency_name_clf
        CurrencyFlagList.CKD -> R.string.currency_name_ckd
        CurrencyFlagList.CLP -> R.string.currency_name_clp
        CurrencyFlagList.CNY -> R.string.currency_name_cny
        CurrencyFlagList.COP -> R.string.currency_name_cop
        CurrencyFlagList.CRC -> R.string.currency_name_crc
        CurrencyFlagList.CUC -> R.string.currency_name_cuc
        CurrencyFlagList.CUP -> R.string.currency_name_cup
        CurrencyFlagList.CVE -> R.string.currency_name_cve
        CurrencyFlagList.CZK -> R.string.currency_name_czk
        CurrencyFlagList.DJF -> R.string.currency_name_djf
        CurrencyFlagList.DKK -> R.string.currency_name_dkk
        CurrencyFlagList.DOP -> R.string.currency_name_dop
        CurrencyFlagList.DZD -> R.string.currency_name_dzd
        CurrencyFlagList.EGP -> R.string.currency_name_egp
        CurrencyFlagList.ERN -> R.string.currency_name_ern
        CurrencyFlagList.ETB -> R.string.currency_name_etb
        CurrencyFlagList.EUR -> R.string.currency_name_eur
        CurrencyFlagList.FJD -> R.string.currency_name_fjd
        CurrencyFlagList.FKP -> R.string.currency_name_fkp
        CurrencyFlagList.FOK -> R.string.currency_name_fok
        CurrencyFlagList.GBP -> R.string.currency_name_gbp
        CurrencyFlagList.GEL -> R.string.currency_name_gel
        CurrencyFlagList.GGP -> R.string.currency_name_ggp
        CurrencyFlagList.GHS -> R.string.currency_name_ghs
        CurrencyFlagList.GIP -> R.string.currency_name_gip
        CurrencyFlagList.GMD -> R.string.currency_name_gmd
        CurrencyFlagList.GNF -> R.string.currency_name_gnf
        CurrencyFlagList.GTQ -> R.string.currency_name_gtq
        CurrencyFlagList.GYD -> R.string.currency_name_gyd
        CurrencyFlagList.HKD -> R.string.currency_name_hkd
        CurrencyFlagList.HNL -> R.string.currency_name_hnl
        CurrencyFlagList.HRK -> R.string.currency_name_hrk
        CurrencyFlagList.HTG -> R.string.currency_name_htg
        CurrencyFlagList.HUF -> R.string.currency_name_huf
        CurrencyFlagList.IDR -> R.string.currency_name_idr
        CurrencyFlagList.ILS -> R.string.currency_name_ils
        CurrencyFlagList.IMP -> R.string.currency_name_imp
        CurrencyFlagList.INR -> R.string.currency_name_inr
        CurrencyFlagList.IQD -> R.string.currency_name_iqd
        CurrencyFlagList.IRR -> R.string.currency_name_irr
        CurrencyFlagList.ISK -> R.string.currency_name_isk
        CurrencyFlagList.JEP -> R.string.currency_name_jep
        CurrencyFlagList.JMD -> R.string.currency_name_jmd
        CurrencyFlagList.JOD -> R.string.currency_name_jod
        CurrencyFlagList.JPY -> R.string.currency_name_jpy
        CurrencyFlagList.KES -> R.string.currency_name_kes
        CurrencyFlagList.KID -> R.string.currency_name_kid
        CurrencyFlagList.KGS -> R.string.currency_name_kgs
        CurrencyFlagList.KHR -> R.string.currency_name_khr
        CurrencyFlagList.KMF -> R.string.currency_name_kmf
        CurrencyFlagList.KPW -> R.string.currency_name_kpw
        CurrencyFlagList.KRW -> R.string.currency_name_krw
        CurrencyFlagList.KWD -> R.string.currency_name_kwd
        CurrencyFlagList.KYD -> R.string.currency_name_kyd
        CurrencyFlagList.KZT -> R.string.currency_name_kzt
        CurrencyFlagList.LAK -> R.string.currency_name_lak
        CurrencyFlagList.LBP -> R.string.currency_name_lbp
        CurrencyFlagList.LKR -> R.string.currency_name_lkr
        CurrencyFlagList.LRD -> R.string.currency_name_lrd
        CurrencyFlagList.LSL -> R.string.currency_name_lsl
        CurrencyFlagList.LYD -> R.string.currency_name_lyd
        CurrencyFlagList.MAD -> R.string.currency_name_mad
        CurrencyFlagList.MDL -> R.string.currency_name_mdl
        CurrencyFlagList.MGA -> R.string.currency_name_mga
        CurrencyFlagList.MKD -> R.string.currency_name_mkd
        CurrencyFlagList.MMK -> R.string.currency_name_mmk
        CurrencyFlagList.MNT -> R.string.currency_name_mnt
        CurrencyFlagList.MOP -> R.string.currency_name_mop
        CurrencyFlagList.MRU -> R.string.currency_name_mru
        CurrencyFlagList.MUR -> R.string.currency_name_mur
        CurrencyFlagList.MVR -> R.string.currency_name_mvr
        CurrencyFlagList.MWK -> R.string.currency_name_mwk
        CurrencyFlagList.MXN -> R.string.currency_name_mxn
        CurrencyFlagList.MYR -> R.string.currency_name_myr
        CurrencyFlagList.MZN -> R.string.currency_name_mzn
        CurrencyFlagList.NAD -> R.string.currency_name_nad
        CurrencyFlagList.NGN -> R.string.currency_name_ngn
        CurrencyFlagList.NIO -> R.string.currency_name_nio
        CurrencyFlagList.NOK -> R.string.currency_name_nok
        CurrencyFlagList.NPR -> R.string.currency_name_npr
        CurrencyFlagList.NZD -> R.string.currency_name_nzd
        CurrencyFlagList.OMR -> R.string.currency_name_omr
        CurrencyFlagList.PAB -> R.string.currency_name_pab
        CurrencyFlagList.PEN -> R.string.currency_name_pen
        CurrencyFlagList.PGK -> R.string.currency_name_pgk
        CurrencyFlagList.PHP -> R.string.currency_name_php
        CurrencyFlagList.PKR -> R.string.currency_name_pkr
        CurrencyFlagList.PLN -> R.string.currency_name_pln
        CurrencyFlagList.PYG -> R.string.currency_name_pyg
        CurrencyFlagList.QAR -> R.string.currency_name_qar
        CurrencyFlagList.RON -> R.string.currency_name_ron
        CurrencyFlagList.RSD -> R.string.currency_name_rsd
        CurrencyFlagList.RUB -> R.string.currency_name_rub
        CurrencyFlagList.RWF -> R.string.currency_name_rwf
        CurrencyFlagList.SAR -> R.string.currency_name_sar
        CurrencyFlagList.SBD -> R.string.currency_name_sbd
        CurrencyFlagList.SCR -> R.string.currency_name_scr
        CurrencyFlagList.SDG -> R.string.currency_name_sdg
        CurrencyFlagList.SEK -> R.string.currency_name_sek
        CurrencyFlagList.SGD -> R.string.currency_name_sgd
        CurrencyFlagList.SHP -> R.string.currency_name_shp
        CurrencyFlagList.SLL -> R.string.currency_name_sll
        CurrencyFlagList.SOS -> R.string.currency_name_sos
        CurrencyFlagList.SRD -> R.string.currency_name_srd
        CurrencyFlagList.SSP -> R.string.currency_name_ssp
        CurrencyFlagList.STN -> R.string.currency_name_stn
        CurrencyFlagList.SVC -> R.string.currency_name_svc
        CurrencyFlagList.SYP -> R.string.currency_name_syp
        CurrencyFlagList.SZL -> R.string.currency_name_szl
        CurrencyFlagList.THB -> R.string.currency_name_thb
        CurrencyFlagList.TJS -> R.string.currency_name_tjs
        CurrencyFlagList.TMT -> R.string.currency_name_tmt
        CurrencyFlagList.TND -> R.string.currency_name_tnd
        CurrencyFlagList.TOP -> R.string.currency_name_top
        CurrencyFlagList.TRY -> R.string.currency_name_try
        CurrencyFlagList.TTD -> R.string.currency_name_ttd
        CurrencyFlagList.TVD -> R.string.currency_name_tvd
        CurrencyFlagList.TWD -> R.string.currency_name_twd
        CurrencyFlagList.TZS -> R.string.currency_name_tzs
        CurrencyFlagList.UAH -> R.string.currency_name_uah
        CurrencyFlagList.UGX -> R.string.currency_name_ugx
        CurrencyFlagList.USD -> R.string.currency_name_usd
        CurrencyFlagList.UYU -> R.string.currency_name_uyu
        CurrencyFlagList.UZS -> R.string.currency_name_uzs
        CurrencyFlagList.VEF -> R.string.currency_name_vef
        CurrencyFlagList.VES -> R.string.currency_name_ves
        CurrencyFlagList.VND -> R.string.currency_name_vnd
        CurrencyFlagList.VUV -> R.string.currency_name_vuv
        CurrencyFlagList.WST -> R.string.currency_name_wst
        CurrencyFlagList.XAF -> R.string.currency_name_xaf
        CurrencyFlagList.XCD -> R.string.currency_name_xcd
        CurrencyFlagList.XOF -> R.string.currency_name_xof
        CurrencyFlagList.XPF -> R.string.currency_name_xpf
        CurrencyFlagList.YER -> R.string.currency_name_yer
        CurrencyFlagList.ZAR -> R.string.currency_name_zar
        CurrencyFlagList.ZMW -> R.string.currency_name_zmw
        CurrencyFlagList.ZWL -> R.string.currency_name_zwl
    }
}
